language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libbz2-dev
            - libcurl4-openssl-dev
            - libfribidi-dev
            - libgtk-3-dev
            - libjpeg-dev
            - libxml2-dev

    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libbz2-dev
            - libcurl4-openssl-dev
            - libfribidi-dev
            - libgtk-3-dev
            - libjpeg-dev
            - libxml2-dev

    - os: osx
      compiler: gcc

    - os: osx
      compiler: clang

    - os: windows
      compiler: gcc

script:
  - if [ $TRAVIS_OS_NAME = windows ]; then mingw32-make; else make; fi
